title: Eduardo Corrêa
description: Seja muito bem vindo(a) ao Blog Eduardo Corrêa!

url: https://eduardocorreaoficial.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Início
    url: /index.html
  - title: Sobre
    url: /about
  - title: Contato
    url: /contact

social:
  github: brianmaierjr
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: eduardo@correaeduardo.com

google_analytics: ""
